entryPoints:
  api:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

accessLog: {}

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: manuelvalverde.dev@gmail.com
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: api

providers:
  docker:
      exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true