# Generated by Django 4.2.7 on 2025-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibrary',
            name='id_source',
            field=models.CharField(null=True),
        ),
    ]
