# Generated by Django 5.2.4 on 2025-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complements',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
