# Generated by Django 5.2.4 on 2025-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_complements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complements',
            field=models.ManyToManyField(blank=True, related_name='is_complement_of', to='product.product'),
        ),
    ]
