# Generated by Django 5.2.4 on 2025-08-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_complements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='complements',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('bundle', 'Bundle')], default='simple'),
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('min_choices', models.PositiveIntegerField(default=0)),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='product.product')),
                ('source_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productoptiongroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='product.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('group', 'product')},
            },
        ),
    ]
