# Generated by Django 5.2.4 on 2025-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default='00000000T', max_length=150, unique=True, verbose_name='dni'),
            preserve_default=False,
        ),
    ]
