# Generated by Django 5.2.4 on 2025-07-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_bill_table_bill_amount_bill_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.bill'),
        ),
    ]
