# Generated by Django 5.2.4 on 2025-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
