# Generated by Django 5.2.4 on 2025-08-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_zone_is_deleted'),
        ('product', '0003_alter_product_complements'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complements',
            field=models.ManyToManyField(blank=True, related_name='order_items_as_complements', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product'),
        ),
    ]
